name: CI / CD workflows for Spring web app

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*' 

jobs:
  build-and-push:
    uses: shahrukhshafique/reusable-workflows/.github/workflows/build.yml@main
    with:
      CODE_REPO: ${{ github.repository }}
    secrets: inherit