name: CI / CD workflows for Spring web app

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*' 

jobs:
  build:
    uses: shahrukhshafique/reusable-workflows/.github/workflows/build.yml@main
    with:
      CODE_REPO: ${{ github.repository }}

 # Second job: Dockerize with the built JAR
  docker-build-and-push:
    uses: shahrukhshafique/reusable-workflows/.github/workflows/dockerbuild-and-push.yml@main
    with:
      CODE_REPO: ${{ github.repository }}
    secrets: inherit