name: CI / CD workflows for Spring web app

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*' 

jobs:
  build-and-push:
    uses: reusable-workflows/workflows/build.yaml@master
    with:
      CODE_REPO: ${{ github.repository }}
    secrets: inherit