name: CI / CD workflows for Spring web app

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*' 
  workflow_dispatch:

jobs:
  build:
    uses: shahrukhshafique/reusable-workflows/.github/workflows/build.yml@main
    with:
      CODE_REPO: ${{ github.repository }}

 # Second job: Dockerize with the built JAR
  docker-build-and-push:
    needs: build  
    uses: shahrukhshafique/reusable-workflows/.github/workflows/dockerbuild-and-push.yml@main
    with:
      CODE_REPO: ${{ github.repository }}
    secrets: inherit

  # Deploy job: App deploy to EKS using helm charts
  helm-upgrade:
    needs: docker-build-and-push  
    uses: shahrukhshafique/reusable-workflows/.github/workflows/helm-deploy.yml@main
    with:
      CODE_REPO: ${{ github.repository }}
    secrets: inherit